import React from "react";
import './Home.css';
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="mui-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://mui.com/">Material UI v5  </a>. Quickly use below links
        to navigate through all components.
      </p>
      <ul>
        <li>
          <Link to="/autocomplete">Autocomplete</Link>
        </li>
        <li>
          <Link to="/button">Button</Link>
        </li>
       
      </ul>
    </div>
  );
};

export default Home;
